GET http://localhost:8080/api/logging/1
Content-Type: application/json
Authorization: Basic name name123
###

GET http://localhost:8080/api/logging/co2sum
Content-Type: application/json
Authorization: Basic name name123
###

GET http://localhost:8080/api/logging/co2sum/1
Content-Type: application/json
Authorization: Basic name name123
###

GET http://localhost:8080/api/logging/userlogs/1
Content-Type: application/json
Authorization: Basic name name123
###

## updatelog/{user_id}/{log's id}. this is s.t. we can add the user id into the database and only that user can update that log
PUT http://localhost:8080/api/logging/updatelog/1/2
Content-Type: application/json
Authorization: Basic name name123

{
    "itemName": "Bulb",
    "itemNotes": "lampcool",
    "itemType": "Consumer Lamp",
    "itemQuantity": 2,
    "createdDate": "2022-01-03"
}

###
DELETE http://localhost:8080/api/logging/deletelog/1/2
Content-Type: application/json
Authorization: Basic name name123


###
POST http://localhost:8080/api/logging/addlog/1
Content-Type: application/json
Authorization: Basic name name123

{
    "itemName": "AAA",
    "itemNotes": "AAAAAA",
    "itemType": "Battery",
    "itemQuantity": 1,
    "createdDate": "2020-03-03"
}

###
POST http://localhost:8080/api/logging/addlog/2
Content-Type: application/json
Authorization: Basic name name123

{
    "itemName": "AAA",
    "itemNotes": "AAAA",
    "itemType": "Battery",
    "itemQuantity": 1,
    "createdDate": "2020-03-03"
}

###
GET http://localhost:8080/api/bins
Content-Type: application/json
Authorization: Basic name name123

###
GET http://localhost:8080/api/bins/1
Content-Type: application/json
Authorization: Basic name name123

###
POST http://localhost:8080/api/bins/addBin
Content-Type: application/json
Authorization: Basic name name123

{
    "postalCode": "123456",
    "address": "somewhere",
    "isIct": "true",
    "isBattery": "false",
    "isBulb": "true"
}

###
PUT http://localhost:8080/api/bins/updateBin/1
Content-Type: application/json
Authorization: Basic name name123

{
    "postalCode": "111111",
    "address": "new place",
    "isIct": "false",
    "isBattery": "false",
    "isBulb": "false"
}

###
POST http://localhost:8080/api/bins/findNearestBin
Content-Type: application/json
Authorization: Basic abiya1 password

{
    "longitude": 103.764216360638,
    "latitude": 1.38442024544603,
    "recycleType": "Bulb"
}

###
DELETE http://localhost:8080/api/bins/deleteBin/2
Content-Type: application/json
Authorization: Basic name name123
