GET http://localhost:8080/logging/
Content-Type: application/json
Authorization: Basic name name123

###
PUT http://localhost:8080/logging/1
Content-Type: application/json
Authorization: Basic name name123

{
    "itemName": "lamp",
    "itemNotes": "lampcool",
    "itemType": "Lamp type lolz",
    "createdDate": "2022-01-03"
}

###

DELETE http://localhost:8080/logging/1


###
POST http://localhost:8080/logging
Content-Type: application/json
Authorization: Basic name name123

{
    "itemName": "newObject",
    "itemNotes": "AAAAAA",
    "itemType": "type",
    "createdDate": "2020-03-03"
}
