GET http://localhost:8080/logging/
Content-Type: application/json
Authorization: Basic name name123

###
PUT http://localhost:8080/logging/1
Content-Type: application/json
Authorization: Basic name name123

{
    "itemName": "lamp",
    "itemNotes": "lampcool",
    "imagePath": "dummyPath1replaced",
    "itemType": "Lamp type lolz",
    "createdDate": "2022-01-03"
}

###

DELETE http://localhost:8080/logging/1
